Knjizara/Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Knjizara.Models
{
    public class Book
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public Genre Genre { get; set; }
        public List <Chapter> Chapters { get; set; }
        public bool Deleted { get; set; }

        public Book(string name,double price,Genre genre,List<Chapter> chapters, bool deleted)
        {           
            this.Name = name;
            this.Price = price;
            this.Genre = genre;
            this.Chapters = chapters;         
        }

        public Book(int id,string name, double price, Genre genre,List<Chapter> chapters, bool deleted)
        {
            this.Id = id;
            this.Name = name;
            this.Price = price;
            this.Genre = genre;
            this.Chapters = chapters;
            this.Deleted = deleted;
        }

        public Book()
        {
            this.Genre = new Genre();

            this.Chapters = new List<Chapter>();

        }
    }
}

Knjizara/Models/Bookstore.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Knjizara.Models
{
    public class Bookstore
    {
        public int Id  { get; set; }
        public string Name { get; set; }
        public List<Book> BookList { get; set; }
    }
}

Knjizara/Models/Chapter.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Knjizara.Models
{
    public class Chapter
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public Chapter(int id,string name)
        {
            this.Id = id;
            this.Name = name;
        }
    }
}

Knjizara/Models/Genre.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Knjizara.Models
{
    public class Genre
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Deleted { get; set; }


        public Genre(int id, string name, bool deleted)
        {
            this.Id = id;
            this.Name = name;
            this.Deleted = deleted;
        }
        public Genre()
        {

        }

        public Genre(string name)
        {
            this.Id = Project.Genres.Count;
            this.Name = name;
            this.Deleted = false;
        }
    }
}

Knjizara/Models/Project.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


namespace Knjizara.Models
{
    public class Project
    {
        public static List<Chapter> ChaptersB1 = new List<Chapter>()
        {
            new Chapter(0, "Chapter 1"),
            new Chapter(1, "Chapter 2"),
            new Chapter(2, "Chapter 3")
        };

        public static List<Chapter> ChaptersB2 = new List<Chapter>()
        {
            new Chapter(0, "The Texan"),
            new Chapter(1, "Clevinger"),
            new Chapter(2, "Havermeyer"),
        };

        public static List<Chapter> ChaptersB3= new List<Chapter>()
        {
            new Chapter(0, "Part 1"),
            new Chapter(1, "Part 2"),
            new Chapter(2, "Part 3"),
        };

        public static List<Chapter> ChaptersB4 = new List<Chapter>()
        {
            new Chapter(0, "Intro"),
            new Chapter(1, "Plot"),
            new Chapter(2, "Ending"),
        };

        public static List<Genre> Genres { get; set; } = new List<Genre>()
        {
            new Genre(0,"Science",false),
            new Genre(1,"Comedy",false),
            new Genre(2,"Horror",false),
            new Genre(3,"Drama",false),
        };

        public static List<Book> BookList { get; set; } = new List<Book>()
        {
            new Book(0, "Martian", 1500, Genres[0],ChaptersB1, true),
            new Book(1, "Catch-22", 1200, Genres[1],ChaptersB2, false),
            new Book(2, "It", 800, Genres[2],ChaptersB3, true),
            new Book(3, "The Great Gatsby", 1000,Genres[3], ChaptersB4,false)
        };



       
           
        

       


        
      


        
    }
}

Knjizara/Controllers/BookStoreController.cs
using Knjizara.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Knjizara.ViewModel;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using Knjizara.Repository.Interfaces;
using Knjizara.Repository;

namespace Knjizara.Controllers
{
    public class BookStoreController : Controller
    {
        private IBookRepository BookRepository = new BookRepository();
        private IGenreRepository GenreRepository = new GenreRepository();

        // GET: BookStore
        public ActionResult Index()
        {
            return View(GenreRepository.GetAll());
        }


        public ActionResult Create(Book b, int genre)
        {

            BookRepository.Create(b, genre);
            return RedirectToAction("Read");
        }

        public ActionResult Read()
        {
            return View(BookRepository.GetAll());
        }

        public ActionResult Update(int id)
        {
            BookGenreViewModel retVal = new BookGenreViewModel();

            retVal.Book = BookRepository.GetById(id);
            retVal.Genres = GenreRepository.GetAll().ToList();
            retVal.SelectedGenre = BookRepository.GetById(id).Genre.Id; // Izabrani id zanra

            return View(retVal);
        }


        [HttpPost]
        public ActionResult Update(BookGenreViewModel b)
        {
            BookRepository.Update(b);
            return RedirectToAction("Read");
        }

        public ActionResult ShowDeleted()
        {                                  
            return View(BookRepository.GetDeleted().ToList());
        }

        public ActionResult Delete(int id)
        {
            BookRepository.Delete(id);

            return RedirectToAction("Read");
        }

        public ActionResult Search()
        {
            return View();
        }

        public ActionResult SearchResult(string name, string criteria)
        {          
            return View(BookRepository.FindBook(name,criteria).ToList());
        }

    }
}

Knjizara/Controllers/ChapterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Knjizara.Controllers
{
    public class ChapterController : Controller
    {
        // GET: Chapter
        public ActionResult Index()
        {

            return View();
        }
    }
}

Knjizara/Controllers/GenreController.cs
using Knjizara.Models;
using Knjizara.Repository;
using Knjizara.Repository.Interfaces;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Web.Mvc;

namespace Knjizara.Controllers
{
    public class GenreController : Controller
    {
        private IGenreRepository GenreRepository = new GenreRepository();
        // GET: Genre
        public ActionResult Index()
        {

            return View(GenreRepository.GetAll());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(string name)
        {
            GenreRepository.Create(name);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
           GenreRepository.Delete(id);                     
           return RedirectToAction("Index");
        }
    }
}

Knjizara/Views/BookStore/Index.cshtml

@{
    ViewBag.Title = "Index";
}
@model IEnumerable<Knjizara.Models.Genre>

<h2>BookShop Home Page</h2>
<hr />
<form method="post" action="/BookStore/Create">
    <table>
        <tr>
            <td colspan="2" align="center" }>
                <b>Add new book</b>
            </td>
        </tr>
        <tr>
            <td>
                Book name:
            </td>
            <td>
                <input type="text" name="name" />
            </td>
        </tr>
        <tr>
            <td>
                Price:
            </td>
            <td>
                <input type="number" name="price" />
            </td>
        </tr>
        <tr>
            <td>
                Genre:
            </td>
            <td>
                <select name="Genre">
                    @foreach (Knjizara.Models.Genre g in Model)
                    {
                        <option value="@g.Id">@g.Name</option>
                    }
                </select>
            </td>
        </tr>
        <tr>
            <td colspan="2" align="right">
                <input type="submit" value="Add" />
            </td>
        </tr>
    </table>
    <a href="/BookStore/Read"> Show all books </a>|
    <a href="/Genre/Create"> Add new genre </a> |
    <a href="/BookStore/ShowDeleted"> Show deleted books </a>

</form>


Knjizara/Views/BookStore/Read.cshtml

@{
    ViewBag.Title = "Read";
}
@model IEnumerable<Knjizara.Models.Book>
<h2>Read</h2>

<Table border='1'>

    <tr>

        <td>
            <b> Id </b>
        </td>

        <td>
            <b> Name of Book</b>
        </td>

        <td>
            <b> Genre</b>
        </td>

        <td>
            <b>Price</b>
        </td>

    </tr>
    @foreach (Knjizara.Models.Book bk in Model)
    {
    <tr>
        <td>
            @bk.Id
        </td>
        <td>
            @bk.Name
        </td>
        <td>
            @bk.Genre.Name
        </td>
        <td>
            @bk.Price
        </td>
        <td>
            <a href="/BookStore/Delete/?id=@bk.Id">Delete</a>
        </td>
        <td>
            <a href="/BookStore/Update/?id=@bk.Id">Edit</a>
        </td>
    </tr>
    }

</Table>

Knjizara/Views/BookStore/Search.cshtml

@{
    ViewBag.Title = "Search";
}



<h2>Search</h2>
<div>
    <form method="get" action="/Bookstore/SearchResult">

        <input type"text" name="name" placeholder="Add search criteria" />

        <select name="criteria">
            <option value="name">Book name</option>
            <option value="chapter">Chapter name</option>
        </select>

        <input type="submit" value="Search" />

    </form>
</div>


    


Knjizara/Views/BookStore/SearchResult.cshtml

@{
    ViewBag.Title = "SearchResult";
}
@model IEnumerable<Knjizara.Models.Book>

<h2>SearchResult</h2>

<Table>
    <tr>
        <th>
             Id 
        </th>
        <th>
             Name of Book
        </th>
        <th>
             Genre
        </th>
        <th>
            Price
        </th>
    </tr>
    @foreach (Knjizara.Models.Book bk in Model)
    {
        <tr>
            <td>
                @bk.Id
            </td>
            <td>
                @bk.Name
            </td>
            <td>
                @bk.Genre.Name
            </td>
            <td>
                @bk.Price
            </td>
        </tr>
    }
</Table>

Knjizara/Views/BookStore/ShowDeleted.cshtml
@{
    ViewBag.Title = "ShowDeleted";
}
@model IEnumerable<Knjizara.Models.Book>
<h2>ShowDeleted</h2>

<Table border='1'>

    <tr>

        <td>
            <b> Id </b>
        </td>

        <td>
            <b> Name of Book</b>
        </td>

        <td>
            <b> Genre</b>
        </td>

        <td>
            <b>Price</b>
        </td>

    </tr>
    @foreach (Knjizara.Models.Book bk in Model)
    {
        <tr>

            <td>
                @bk.Id
            </td>

            <td>
                @bk.Name
            </td>

            <td>
                @bk.Genre.Name
            </td>

            <td>
                @bk.Price
            </td>

            

        </tr>
    }

</Table>

Knjizara/Views/BookStore/Update.cshtml

@{
    ViewBag.Title = "Update";
}
@model Knjizara.ViewModel.BookGenreViewModel


<h2>Edit book data</h2>

<form method="post" action="/BookStore/Update">
    <table>
        <tr>
            <td colspan="2" align="center" }>
                <b>Edit book data</b>
            </td>
        </tr>
        <tr>
            <td>
                Book name:
            </td>
            <td>
                <input type="hidden" name="Book.id" value="@Model.Book.Id" />
                <input type="text" name="Book.name" value="@Model.Book.Name" />
            </td>
        </tr>
        <tr>
            <td>
                Price:
            </td>
            <td>
                <input type="number" name="Book.price" value="@Model.Book.Price" />
            </td>
        </tr>
        <tr>
            <td>
                Genre:
            </td>
            <td>
                <select name="SelectedGenre">
                    @foreach (Knjizara.Models.Genre g in Model.Genres)
                    {
                        if (g.Id == Model.SelectedGenre)
                        {
                            <option value="@g.Id" selected>@g.Name</option>
                        }
                        else
                        {
                            <option value="@g.Id">@g.Name</option>
                        }

                    }
                </select>
            </td>
        </tr>
        <tr>
            <td colspan="2" align="right">
                <input type="submit" value="Save changes" />
            </td>
        </tr>
    </table>
    

</form>


Knjizara/Views/Genre/Create.cshtml

@{
    ViewBag.Title = "Create";
}

<h2>Add new genre</h2>

<div class="genre-add">
    <form method="post" >
        <label for="name">Genre</label>
        <input type="text" name="name" />
        <input type="submit" value="Add" />
    </form>
</div>

Knjizara/Views/Genre/Index.cshtml

@{
    ViewBag.Title = "Index";
}
@model IEnumerable<Knjizara.Models.Genre>

<h2>Add new genre</h2>
<table>
    <tr>
        <th>Id</th>
        <th>Genre</th>
    </tr>

    @foreach (Knjizara.Models.Genre gr in Model)
    {
        <tr>
            <td>
                @gr.Id
            </td>
            <td>
                @gr.Name
            </td>
            <td>
                <a href="/Genre/Delete/?id=@gr.Id">Delete</a>
            </td>

        </tr>
    }
</table>
<a href="/Genre/Create">Add new genre</a>


Knjizara/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - BookShop</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        
        <div class="container">

            <div class="navbar-header">
               <img class="logo" src="~/Content/Images/logo.png" width="60" height="60" />
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                @Html.ActionLink("BookShop", "Index", "Bookstore", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "BookStore")</li>
                    <li>@Html.ActionLink("Search", "Search", "Bookstore")</li>                   
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
           

        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>